using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HospitalPm.Infrastructure.Persistence.Migrations;

/// <summary>
/// Seeds the starter equipment types and their category links.
///
/// Types are seeded so a hospital's first Excel import can auto-match
/// instead of requiring manual mapping for every row. Hospitals may add
/// their own; is_seeded distinguishes shipped rows from local additions so
/// a future upgrade can refresh ours without touching theirs.
///
/// Three categories are deliberately handled differently:
///
///   implantable          - no types seeded. Implants are placed inside a
///                          patient, receive no preventive maintenance, and
///                          tracking one individually would mean recording
///                          which patient has it. That is patient data, which
///                          this product does not hold.
///   prosthetic-orthotic  - workshop fabrication equipment only. A fitted
///                          prosthesis belongs to a patient; the vacuum
///                          former that made it belongs to the hospital.
///   home-healthcare      - hospital-owned loan-pool units only, which have a
///                          store location and a maintenance history. Not
///                          devices a patient owns.
///
/// Idempotent: types match on (tenant_id, code) and links on their composite
/// key, both ON CONFLICT DO NOTHING. Links resolve ids by code rather than
/// hardcoding them, since identity values differ per install.
/// </summary>
public partial class SeedEquipmentTypes : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
            INSERT INTO equipment_type (tenant_id, code, name, is_seeded, is_active)
            VALUES
                (1, 'ecg-machine', 'ECG machine', true, true),
                (1, 'tmt-system', 'TMT / stress test system', true, true),
                (1, 'holter-monitor', 'Holter monitor', true, true),
                (1, 'spirometer-pft', 'Spirometer / PFT system', true, true),
                (1, 'eeg-machine', 'EEG machine', true, true),
                (1, 'emg-ncv-machine', 'EMG / NCV machine', true, true),
                (1, 'audiometer', 'Audiometer', true, true),
                (1, 'tympanometer', 'Tympanometer', true, true),
                (1, 'diagnostic-endoscope', 'Diagnostic endoscope', true, true),
                (1, 'colposcope', 'Colposcope', true, true),
                (1, 'vascular-doppler', 'Vascular Doppler', true, true),
                (1, 'ventilator', 'Ventilator', true, true),
                (1, 'bipap-cpap-unit', 'BiPAP / CPAP unit', true, true),
                (1, 'nebulizer', 'Nebulizer', true, true),
                (1, 'hemodialysis-machine', 'Hemodialysis machine', true, true),
                (1, 'phototherapy-unit', 'Phototherapy unit', true, true),
                (1, 'shortwave-diathermy', 'Shortwave diathermy', true, true),
                (1, 'defibrillator', 'Defibrillator', true, true),
                (1, 'cardiac-ablation-unit', 'Cardiac ablation unit', true, true),
                (1, 'multipara-monitor', 'Multipara patient monitor', true, true),
                (1, 'pulse-oximeter', 'Pulse oximeter', true, true),
                (1, 'nibp-monitor', 'NIBP monitor', true, true),
                (1, 'cardiac-telemetry', 'Cardiac telemetry system', true, true),
                (1, 'fetal-monitor-ctg', 'Fetal monitor (CTG)', true, true),
                (1, 'capnograph', 'Capnograph', true, true),
                (1, 'central-monitoring-station', 'Central monitoring station', true, true),
                (1, 'bis-monitor', 'BIS / depth-of-anaesthesia monitor', true, true),
                (1, 'icu-ventilator', 'ICU ventilator', true, true),
                (1, 'anaesthesia-workstation', 'Anaesthesia workstation', true, true),
                (1, 'heart-lung-machine', 'Heart-lung machine', true, true),
                (1, 'ecmo-machine', 'ECMO machine', true, true),
                (1, 'iabp', 'Intra-aortic balloon pump', true, true),
                (1, 'operating-table', 'Operating table', true, true),
                (1, 'ot-light', 'OT light', true, true),
                (1, 'electrosurgical-unit', 'Electrosurgical unit (cautery)', true, true),
                (1, 'surgical-microscope', 'Surgical microscope', true, true),
                (1, 'laparoscopy-tower', 'Laparoscopy tower', true, true),
                (1, 'arthroscopy-system', 'Arthroscopy system', true, true),
                (1, 'harmonic-scalpel', 'Harmonic scalpel', true, true),
                (1, 'surgical-suction-unit', 'Surgical suction unit', true, true),
                (1, 'pneumatic-tourniquet', 'Pneumatic tourniquet', true, true),
                (1, 'surgical-drill-system', 'Surgical drill system', true, true),
                (1, 'ultrasound-therapy-unit', 'Ultrasound therapy unit', true, true),
                (1, 'tens-unit', 'TENS unit', true, true),
                (1, 'traction-unit', 'Traction unit', true, true),
                (1, 'cpm-machine', 'CPM machine', true, true),
                (1, 'therapy-treadmill', 'Therapy treadmill', true, true),
                (1, 'wax-bath', 'Wax bath', true, true),
                (1, 'ift-unit', 'IFT unit', true, true),
                (1, 'wheelchair', 'Wheelchair', true, true),
                (1, 'walker', 'Walker', true, true),
                (1, 'patient-hoist', 'Patient hoist / lift', true, true),
                (1, 'commode-chair', 'Commode chair', true, true),
                (1, 'steam-sterilizer', 'Steam sterilizer / autoclave', true, true),
                (1, 'eto-sterilizer', 'ETO sterilizer', true, true),
                (1, 'plasma-sterilizer', 'Plasma sterilizer', true, true),
                (1, 'washer-disinfector', 'Washer disinfector', true, true),
                (1, 'uv-disinfection-unit', 'UV disinfection unit', true, true),
                (1, 'hepa-air-purification', 'HEPA / air purification unit', true, true),
                (1, 'hematology-analyzer', 'Hematology analyzer', true, true),
                (1, 'biochemistry-analyzer', 'Biochemistry analyzer', true, true),
                (1, 'immunoassay-analyzer', 'Immunoassay analyzer', true, true),
                (1, 'blood-gas-analyzer', 'Blood gas analyzer', true, true),
                (1, 'coagulation-analyzer', 'Coagulation analyzer', true, true),
                (1, 'urine-analyzer', 'Urine analyzer', true, true),
                (1, 'centrifuge', 'Centrifuge', true, true),
                (1, 'laboratory-microscope', 'Laboratory microscope', true, true),
                (1, 'laboratory-incubator', 'Laboratory incubator', true, true),
                (1, 'pcr-system', 'PCR / RT-PCR system', true, true),
                (1, 'elisa-reader-washer', 'ELISA reader / washer', true, true),
                (1, 'blood-bank-refrigerator', 'Blood bank refrigerator', true, true),
                (1, 'deep-freezer', 'Deep freezer', true, true),
                (1, 'water-bath', 'Water bath', true, true),
                (1, 'slide-stainer', 'Slide stainer', true, true),
                (1, 'fixed-xray', 'Fixed X-ray unit', true, true),
                (1, 'mobile-xray', 'Mobile X-ray unit', true, true),
                (1, 'ct-scanner', 'CT scanner', true, true),
                (1, 'mri-scanner', 'MRI scanner', true, true),
                (1, 'ultrasound-scanner', 'Ultrasound scanner', true, true),
                (1, 'colour-doppler', 'Colour Doppler', true, true),
                (1, 'mammography-unit', 'Mammography unit', true, true),
                (1, 'c-arm', 'C-arm', true, true),
                (1, 'cath-lab-dsa', 'Cath lab / DSA system', true, true),
                (1, 'bone-densitometer', 'Bone densitometer (DEXA)', true, true),
                (1, 'gamma-camera-spect', 'Gamma camera / SPECT', true, true),
                (1, 'pet-ct', 'PET-CT scanner', true, true),
                (1, 'cr-dr-system', 'CR / DR system', true, true),
                (1, 'pacs-workstation', 'PACS workstation', true, true),
                (1, 'infusion-pump', 'Infusion pump', true, true),
                (1, 'syringe-pump', 'Syringe pump', true, true),
                (1, 'pca-pump', 'PCA pump', true, true),
                (1, 'enteral-feeding-pump', 'Enteral feeding pump', true, true),
                (1, 'anaesthesia-vaporizer', 'Anaesthesia vaporizer', true, true),
                (1, 'insulin-pump', 'Insulin pump', true, true),
                (1, 'electric-hospital-bed', 'Electric hospital bed', true, true),
                (1, 'icu-bed', 'ICU bed', true, true),
                (1, 'patient-trolley', 'Patient trolley / stretcher', true, true),
                (1, 'examination-couch', 'Examination couch', true, true),
                (1, 'suction-machine', 'Suction machine', true, true),
                (1, 'air-mattress', 'Alternating pressure mattress', true, true),
                (1, 'patient-warming-unit', 'Patient warming unit', true, true),
                (1, 'weighing-scale', 'Weighing scale', true, true),
                (1, 'dental-chair-unit', 'Dental chair unit', true, true),
                (1, 'dental-xray', 'Dental X-ray unit', true, true),
                (1, 'opg-machine', 'OPG machine', true, true),
                (1, 'dental-autoclave', 'Dental autoclave', true, true),
                (1, 'light-cure-unit', 'Light cure unit', true, true),
                (1, 'ultrasonic-scaler', 'Ultrasonic scaler', true, true),
                (1, 'dental-compressor', 'Dental compressor', true, true),
                (1, 'amalgamator', 'Amalgamator', true, true),
                (1, 'slit-lamp', 'Slit lamp', true, true),
                (1, 'autorefractometer', 'Autorefractometer', true, true),
                (1, 'fundus-camera', 'Fundus camera', true, true),
                (1, 'phacoemulsification-unit', 'Phacoemulsification unit', true, true),
                (1, 'ophthalmic-ab-scan', 'Ophthalmic A-scan / B-scan', true, true),
                (1, 'perimeter', 'Perimeter', true, true),
                (1, 'oct-machine', 'OCT machine', true, true),
                (1, 'keratometer', 'Keratometer', true, true),
                (1, 'yag-laser', 'YAG laser', true, true),
                (1, 'tonometer', 'Tonometer', true, true),
                (1, 'infant-radiant-warmer', 'Infant radiant warmer', true, true),
                (1, 'infant-incubator', 'Infant incubator', true, true),
                (1, 'neonatal-ventilator', 'Neonatal ventilator', true, true),
                (1, 'neonatal-cpap', 'Neonatal CPAP', true, true),
                (1, 'infant-phototherapy-unit', 'Infant phototherapy unit', true, true),
                (1, 'infant-resuscitator', 'Infant resuscitator', true, true),
                (1, 'transport-incubator', 'Transport incubator', true, true),
                (1, 'bilirubinometer', 'Bilirubinometer', true, true),
                (1, 'oxygen-concentrator-loan', 'Oxygen concentrator (loan pool)', true, true),
                (1, 'nebulizer-loan', 'Nebulizer (loan pool)', true, true),
                (1, 'cpap-loan', 'CPAP unit (loan pool)', true, true),
                (1, 'hospital-bed-loan', 'Hospital bed (loan pool)', true, true),
                (1, 'po-vacuum-former', 'P&O vacuum forming machine', true, true),
                (1, 'po-oven', 'P&O thermoplastic oven', true, true),
                (1, 'po-grinder', 'P&O grinding / sanding machine', true, true),
                (1, 'po-casting-bench', 'P&O plaster casting bench', true, true),
                (1, 'po-router', 'P&O router / trimmer', true, true)
            ON CONFLICT (tenant_id, code) DO NOTHING;");

        migrationBuilder.Sql(@"
            INSERT INTO equipment_type_category (tenant_id, equipment_type_id, category_id, is_primary)
            SELECT 1, et.id, c.id, v.is_primary
            FROM (VALUES
                    ('ecg-machine', 'diagnostic', true),
                    ('ecg-machine', 'monitoring', false),
                    ('tmt-system', 'diagnostic', true),
                    ('holter-monitor', 'diagnostic', true),
                    ('holter-monitor', 'monitoring', false),
                    ('spirometer-pft', 'diagnostic', true),
                    ('eeg-machine', 'diagnostic', true),
                    ('eeg-machine', 'monitoring', false),
                    ('emg-ncv-machine', 'diagnostic', true),
                    ('audiometer', 'diagnostic', true),
                    ('tympanometer', 'diagnostic', true),
                    ('diagnostic-endoscope', 'diagnostic', true),
                    ('colposcope', 'diagnostic', true),
                    ('vascular-doppler', 'diagnostic', true),
                    ('vascular-doppler', 'imaging', false),
                    ('ventilator', 'therapeutic', true),
                    ('ventilator', 'life-support', false),
                    ('bipap-cpap-unit', 'therapeutic', true),
                    ('nebulizer', 'therapeutic', true),
                    ('hemodialysis-machine', 'therapeutic', true),
                    ('hemodialysis-machine', 'life-support', false),
                    ('phototherapy-unit', 'therapeutic', true),
                    ('shortwave-diathermy', 'therapeutic', true),
                    ('shortwave-diathermy', 'rehabilitation', false),
                    ('defibrillator', 'therapeutic', true),
                    ('defibrillator', 'life-support', false),
                    ('cardiac-ablation-unit', 'therapeutic', true),
                    ('cardiac-ablation-unit', 'surgical', false),
                    ('multipara-monitor', 'monitoring', true),
                    ('pulse-oximeter', 'monitoring', true),
                    ('nibp-monitor', 'monitoring', true),
                    ('cardiac-telemetry', 'monitoring', true),
                    ('fetal-monitor-ctg', 'monitoring', true),
                    ('fetal-monitor-ctg', 'diagnostic', false),
                    ('capnograph', 'monitoring', true),
                    ('central-monitoring-station', 'monitoring', true),
                    ('bis-monitor', 'monitoring', true),
                    ('icu-ventilator', 'life-support', true),
                    ('icu-ventilator', 'therapeutic', false),
                    ('anaesthesia-workstation', 'life-support', true),
                    ('anaesthesia-workstation', 'surgical', false),
                    ('heart-lung-machine', 'life-support', true),
                    ('heart-lung-machine', 'surgical', false),
                    ('ecmo-machine', 'life-support', true),
                    ('ecmo-machine', 'therapeutic', false),
                    ('iabp', 'life-support', true),
                    ('iabp', 'therapeutic', false),
                    ('operating-table', 'surgical', true),
                    ('ot-light', 'surgical', true),
                    ('electrosurgical-unit', 'surgical', true),
                    ('surgical-microscope', 'surgical', true),
                    ('laparoscopy-tower', 'surgical', true),
                    ('arthroscopy-system', 'surgical', true),
                    ('harmonic-scalpel', 'surgical', true),
                    ('surgical-suction-unit', 'surgical', true),
                    ('pneumatic-tourniquet', 'surgical', true),
                    ('surgical-drill-system', 'surgical', true),
                    ('ultrasound-therapy-unit', 'rehabilitation', true),
                    ('ultrasound-therapy-unit', 'therapeutic', false),
                    ('tens-unit', 'rehabilitation', true),
                    ('tens-unit', 'therapeutic', false),
                    ('traction-unit', 'rehabilitation', true),
                    ('cpm-machine', 'rehabilitation', true),
                    ('therapy-treadmill', 'rehabilitation', true),
                    ('wax-bath', 'rehabilitation', true),
                    ('ift-unit', 'rehabilitation', true),
                    ('ift-unit', 'therapeutic', false),
                    ('wheelchair', 'assistive', true),
                    ('wheelchair', 'patient-care', false),
                    ('walker', 'assistive', true),
                    ('patient-hoist', 'assistive', true),
                    ('patient-hoist', 'patient-care', false),
                    ('commode-chair', 'assistive', true),
                    ('commode-chair', 'patient-care', false),
                    ('steam-sterilizer', 'preventive', true),
                    ('eto-sterilizer', 'preventive', true),
                    ('plasma-sterilizer', 'preventive', true),
                    ('washer-disinfector', 'preventive', true),
                    ('uv-disinfection-unit', 'preventive', true),
                    ('hepa-air-purification', 'preventive', true),
                    ('hematology-analyzer', 'laboratory-diagnostic', true),
                    ('hematology-analyzer', 'diagnostic', false),
                    ('biochemistry-analyzer', 'laboratory-diagnostic', true),
                    ('biochemistry-analyzer', 'diagnostic', false),
                    ('immunoassay-analyzer', 'laboratory-diagnostic', true),
                    ('immunoassay-analyzer', 'diagnostic', false),
                    ('blood-gas-analyzer', 'laboratory-diagnostic', true),
                    ('blood-gas-analyzer', 'diagnostic', false),
                    ('coagulation-analyzer', 'laboratory-diagnostic', true),
                    ('coagulation-analyzer', 'diagnostic', false),
                    ('urine-analyzer', 'laboratory-diagnostic', true),
                    ('urine-analyzer', 'diagnostic', false),
                    ('centrifuge', 'laboratory-diagnostic', true),
                    ('laboratory-microscope', 'laboratory-diagnostic', true),
                    ('laboratory-incubator', 'laboratory-diagnostic', true),
                    ('pcr-system', 'laboratory-diagnostic', true),
                    ('pcr-system', 'diagnostic', false),
                    ('elisa-reader-washer', 'laboratory-diagnostic', true),
                    ('blood-bank-refrigerator', 'laboratory-diagnostic', true),
                    ('deep-freezer', 'laboratory-diagnostic', true),
                    ('water-bath', 'laboratory-diagnostic', true),
                    ('slide-stainer', 'laboratory-diagnostic', true),
                    ('fixed-xray', 'imaging', true),
                    ('fixed-xray', 'diagnostic', false),
                    ('mobile-xray', 'imaging', true),
                    ('mobile-xray', 'diagnostic', false),
                    ('ct-scanner', 'imaging', true),
                    ('ct-scanner', 'diagnostic', false),
                    ('mri-scanner', 'imaging', true),
                    ('mri-scanner', 'diagnostic', false),
                    ('ultrasound-scanner', 'imaging', true),
                    ('ultrasound-scanner', 'diagnostic', false),
                    ('colour-doppler', 'imaging', true),
                    ('colour-doppler', 'diagnostic', false),
                    ('mammography-unit', 'imaging', true),
                    ('mammography-unit', 'diagnostic', false),
                    ('c-arm', 'imaging', true),
                    ('c-arm', 'surgical', false),
                    ('cath-lab-dsa', 'imaging', true),
                    ('cath-lab-dsa', 'surgical', false),
                    ('cath-lab-dsa', 'diagnostic', false),
                    ('bone-densitometer', 'imaging', true),
                    ('bone-densitometer', 'diagnostic', false),
                    ('gamma-camera-spect', 'imaging', true),
                    ('gamma-camera-spect', 'diagnostic', false),
                    ('pet-ct', 'imaging', true),
                    ('pet-ct', 'diagnostic', false),
                    ('cr-dr-system', 'imaging', true),
                    ('pacs-workstation', 'imaging', true),
                    ('infusion-pump', 'drug-delivery', true),
                    ('infusion-pump', 'patient-care', false),
                    ('syringe-pump', 'drug-delivery', true),
                    ('syringe-pump', 'patient-care', false),
                    ('pca-pump', 'drug-delivery', true),
                    ('enteral-feeding-pump', 'drug-delivery', true),
                    ('enteral-feeding-pump', 'patient-care', false),
                    ('anaesthesia-vaporizer', 'drug-delivery', true),
                    ('anaesthesia-vaporizer', 'surgical', false),
                    ('insulin-pump', 'drug-delivery', true),
                    ('electric-hospital-bed', 'patient-care', true),
                    ('icu-bed', 'patient-care', true),
                    ('patient-trolley', 'patient-care', true),
                    ('examination-couch', 'patient-care', true),
                    ('suction-machine', 'patient-care', true),
                    ('suction-machine', 'therapeutic', false),
                    ('air-mattress', 'patient-care', true),
                    ('air-mattress', 'preventive', false),
                    ('patient-warming-unit', 'patient-care', true),
                    ('patient-warming-unit', 'therapeutic', false),
                    ('weighing-scale', 'patient-care', true),
                    ('dental-chair-unit', 'dental', true),
                    ('dental-xray', 'dental', true),
                    ('dental-xray', 'imaging', false),
                    ('opg-machine', 'dental', true),
                    ('opg-machine', 'imaging', false),
                    ('dental-autoclave', 'dental', true),
                    ('dental-autoclave', 'preventive', false),
                    ('light-cure-unit', 'dental', true),
                    ('ultrasonic-scaler', 'dental', true),
                    ('dental-compressor', 'dental', true),
                    ('amalgamator', 'dental', true),
                    ('slit-lamp', 'ophthalmic', true),
                    ('slit-lamp', 'diagnostic', false),
                    ('autorefractometer', 'ophthalmic', true),
                    ('autorefractometer', 'diagnostic', false),
                    ('fundus-camera', 'ophthalmic', true),
                    ('fundus-camera', 'imaging', false),
                    ('phacoemulsification-unit', 'ophthalmic', true),
                    ('phacoemulsification-unit', 'surgical', false),
                    ('ophthalmic-ab-scan', 'ophthalmic', true),
                    ('ophthalmic-ab-scan', 'imaging', false),
                    ('perimeter', 'ophthalmic', true),
                    ('perimeter', 'diagnostic', false),
                    ('oct-machine', 'ophthalmic', true),
                    ('oct-machine', 'imaging', false),
                    ('keratometer', 'ophthalmic', true),
                    ('keratometer', 'diagnostic', false),
                    ('yag-laser', 'ophthalmic', true),
                    ('yag-laser', 'surgical', false),
                    ('tonometer', 'ophthalmic', true),
                    ('tonometer', 'diagnostic', false),
                    ('infant-radiant-warmer', 'neonatal', true),
                    ('infant-radiant-warmer', 'therapeutic', false),
                    ('infant-incubator', 'neonatal', true),
                    ('infant-incubator', 'life-support', false),
                    ('neonatal-ventilator', 'neonatal', true),
                    ('neonatal-ventilator', 'life-support', false),
                    ('neonatal-ventilator', 'therapeutic', false),
                    ('neonatal-cpap', 'neonatal', true),
                    ('neonatal-cpap', 'therapeutic', false),
                    ('infant-phototherapy-unit', 'neonatal', true),
                    ('infant-phototherapy-unit', 'therapeutic', false),
                    ('infant-resuscitator', 'neonatal', true),
                    ('infant-resuscitator', 'life-support', false),
                    ('transport-incubator', 'neonatal', true),
                    ('transport-incubator', 'life-support', false),
                    ('bilirubinometer', 'neonatal', true),
                    ('bilirubinometer', 'diagnostic', false),
                    ('oxygen-concentrator-loan', 'home-healthcare', true),
                    ('oxygen-concentrator-loan', 'therapeutic', false),
                    ('nebulizer-loan', 'home-healthcare', true),
                    ('nebulizer-loan', 'therapeutic', false),
                    ('cpap-loan', 'home-healthcare', true),
                    ('cpap-loan', 'therapeutic', false),
                    ('hospital-bed-loan', 'home-healthcare', true),
                    ('hospital-bed-loan', 'patient-care', false),
                    ('po-vacuum-former', 'prosthetic-orthotic', true),
                    ('po-oven', 'prosthetic-orthotic', true),
                    ('po-grinder', 'prosthetic-orthotic', true),
                    ('po-casting-bench', 'prosthetic-orthotic', true),
                    ('po-router', 'prosthetic-orthotic', true)
                 ) AS v(type_code, category_code, is_primary)
            JOIN equipment_type et ON et.code = v.type_code AND et.tenant_id = 1
            JOIN category       c  ON c.code  = v.category_code AND c.tenant_id = 1
            ON CONFLICT (equipment_type_id, category_id) DO NOTHING;");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
        => throw new NotSupportedException(
            "Migrations are forward-only. Recovery is restore-from-backup, not a down-migration.");
}
