using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HospitalPm.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class PmVendorReports : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Idempotent, like the other schema changes, so a re-run is harmless.
            migrationBuilder.Sql(@"
                -- Who does a PM. Every schedule and completion so far was the hospital's own team.
                ALTER TABLE pm_schedule ADD COLUMN IF NOT EXISTS performed_by integer NOT NULL DEFAULT 10;
                ALTER TABLE pm_completion ADD COLUMN IF NOT EXISTS performed_by integer NOT NULL DEFAULT 10;
                ALTER TABLE pm_completion ADD COLUMN IF NOT EXISTS vendor_name varchar(200) NULL;

                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_pm_schedule_performed_by') THEN
                        ALTER TABLE pm_schedule
                            ADD CONSTRAINT ck_pm_schedule_performed_by CHECK (performed_by IN (10, 20));
                    END IF;

                    -- A vendor's PM names the vendor as it was at the time; an in-house one names none.
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_pm_completion_performed_by') THEN
                        ALTER TABLE pm_completion
                            ADD CONSTRAINT ck_pm_completion_performed_by CHECK (
                                (performed_by = 10 AND vendor_name IS NULL)
                                OR (performed_by = 20 AND vendor_name IS NOT NULL AND length(btrim(vendor_name)) > 0));
                    END IF;
                END
                $$;

                -- The report files. The description is here and the bytes are in the table below,
                -- so the audit trigger records a few lines of text and not the whole file a second
                -- time in the audit log.
                CREATE TABLE IF NOT EXISTS pm_task_attachment (
                    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id integer NOT NULL DEFAULT 1,
                    pm_task_id integer NOT NULL REFERENCES pm_task (id) ON DELETE RESTRICT,
                    file_name varchar(255) NOT NULL,
                    content_type varchar(100) NOT NULL,
                    size_bytes integer NOT NULL CHECK (size_bytes > 0),
                    uploaded_by_user_id integer NOT NULL REFERENCES app_user (id) ON DELETE RESTRICT,
                    uploaded_at_utc timestamp with time zone NOT NULL DEFAULT now()
                );

                CREATE INDEX IF NOT EXISTS ix_pm_task_attachment_task ON pm_task_attachment (pm_task_id);

                CREATE TABLE IF NOT EXISTS pm_task_attachment_data (
                    attachment_id integer PRIMARY KEY REFERENCES pm_task_attachment (id) ON DELETE CASCADE,
                    tenant_id integer NOT NULL DEFAULT 1,
                    data bytea NOT NULL
                );

                -- Every table carries tenant_id. For a database that already has the table without it.
                ALTER TABLE pm_task_attachment_data ADD COLUMN IF NOT EXISTS tenant_id integer NOT NULL DEFAULT 1;

                -- A file is never edited. A wrong one is removed by an Administrator and uploaded again.
                CREATE OR REPLACE FUNCTION fn_pm_task_attachment_no_update() RETURNS trigger
                LANGUAGE plpgsql AS $fn$
                BEGIN
                    RAISE EXCEPTION 'Attachment % is a record and cannot be changed; remove it and upload again', OLD.id
                        USING ERRCODE = 'check_violation';
                END;
                $fn$;

                DROP TRIGGER IF EXISTS trg_pm_task_attachment_no_update ON pm_task_attachment;
                CREATE TRIGGER trg_pm_task_attachment_no_update
                    BEFORE UPDATE ON pm_task_attachment
                    FOR EACH ROW EXECUTE FUNCTION fn_pm_task_attachment_no_update();

                DROP TRIGGER IF EXISTS trg_pm_task_attachment_audit ON pm_task_attachment;
                CREATE TRIGGER trg_pm_task_attachment_audit
                    AFTER INSERT OR UPDATE OR DELETE ON pm_task_attachment
                    FOR EACH ROW EXECUTE FUNCTION fn_audit_row();");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
}
